/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jwiringpi_JWiringPiInterfaceImpl */

#ifndef _Included_jwiringpi_JWiringPiInterfaceImpl
#define _Included_jwiringpi_JWiringPiInterfaceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiSetup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiSetup
  (JNIEnv *, jobject);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiSetupGpio
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiSetupGpio
  (JNIEnv *, jobject);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiSetupPhys
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiSetupPhys
  (JNIEnv *, jobject);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiSetupSys
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiSetupSys
  (JNIEnv *, jobject);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    pinMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_pinMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    pullUpDnControl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_pullUpDnControl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    digitalWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_digitalWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    pwmWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_pwmWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    digitalRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_digitalRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    analogRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_analogRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    analogWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_analogWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    millis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_millis
  (JNIEnv *, jobject);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    micros
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_micros
  (JNIEnv *, jobject);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    delay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_delay
  (JNIEnv *, jobject, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    delayMicroseconds
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_delayMicroseconds
  (JNIEnv *, jobject, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiSPISetup
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiSPISetup
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiSPIDataRW
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiSPIDataRW
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiI2CSetup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiI2CSetup
  (JNIEnv *, jobject, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiI2CRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiI2CRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiI2CWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiI2CWrite__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiI2CWrite
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiI2CWrite__I_3BI
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiI2CWriteReg8
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiI2CWriteReg8
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiI2CWriteReg16
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiI2CWriteReg16
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiI2CReadReg8
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiI2CReadReg8
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jwiringpi_JWiringPiInterfaceImpl
 * Method:    wiringPiI2CReadReg16
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jwiringpi_JWiringPiInterfaceImpl_wiringPiI2CReadReg16
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
